{
  "uid" : "c551a5f531352097",
  "name" : "test_xfail",
  "fullName" : "tests.test_marks.TestMarks#test_xfail",
  "historyId" : "a44cab49732a0aa43a757be1adf99317",
  "time" : {
    "start" : 1589120411364,
    "stop" : 1589120411365,
    "duration" : 1
  },
  "description" : "\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        ",
  "descriptionHtml" : "<pre><code>    Indicate that you expect it to fail\n    这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n    这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n</code></pre>\n",
  "status" : "skipped",
  "statusMessage" : "AssertionError: assert 0",
  "statusTrace" : "self = <tests.test_marks.TestMarks object at 0x00000210BD95E850>\n\n    @pytest.mark.xfail\n    def test_xfail(self):\n        \"\"\"\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        \"\"\"\n>       assert 0\nE       assert 0\n\ntests\\test_marks.py:22: AssertionError",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_marks"
  }, {
    "name" : "subSuite",
    "value" : "TestMarks"
  }, {
    "name" : "host",
    "value" : "8S9K3DZP3JRJTZY"
  }, {
    "name" : "thread",
    "value" : "17372-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_marks"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "xfail" ]
  },
  "source" : "c551a5f531352097.json",
  "parameterValues" : [ ]
}