{"name": "test_xfail_not_run", "status": "skipped", "statusDetails": {"message": "_pytest.outcomes.XFailed: [NOTRUN]", "trace": "cls = <class '_pytest.runner.CallInfo'>, func = <function call_runtest_hook.<locals>.<lambda> at 0x000002042CBEDB80>, when = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(cls, func, when, reraise=None) -> \"CallInfo\":\n        #: context of invocation: one of \"setup\", \"call\",\n        #: \"teardown\", \"memocollect\"\n        start = time()\n        excinfo = None\n        try:\n>           result = func()\n\nd:\\python\\python38\\lib\\site-packages\\_pytest\\runner.py:244: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nd:\\python\\python38\\lib\\site-packages\\_pytest\\runner.py:217: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\nd:\\python\\python38\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\nd:\\python\\python38\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\nd:\\python\\python38\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\nd:\\python\\python38\\lib\\site-packages\\_pytest\\skipping.py:93: in pytest_runtest_setup\n    check_xfail_no_run(item)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nitem = <Function test_xfail_not_run>\n\n    def check_xfail_no_run(item):\n        \"\"\"check xfail(run=False)\"\"\"\n        if not item.config.option.runxfail:\n            evalxfail = item._store[evalxfail_key]\n            if evalxfail.istrue():\n                if not evalxfail.get(\"run\", True):\n>                   xfail(\"[NOTRUN] \" + evalxfail.getexplanation())\nE                   _pytest.outcomes.XFailed: [NOTRUN]\n\nd:\\python\\python38\\lib\\site-packages\\_pytest\\skipping.py:111: XFailed"}, "description": "run=false 表示不执行这条用例", "start": 1589121931739, "stop": 1589121931739, "uuid": "8359ac66-37a4-48db-ac91-a1166edf24be", "historyId": "e4c8f58bb9381dbcdd35cf7a17339a5f", "testCaseId": "a540d15f54461582abcd1bb98563314d", "fullName": "tests.test_marks.TestMarks#test_xfail_not_run", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_marks"}, {"name": "subSuite", "value": "TestMarks"}, {"name": "host", "value": "8S9K3DZP3JRJTZY"}, {"name": "thread", "value": "10944-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_marks"}]}